[project]
name = "bench_xecg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fvcore>=0.1.5.post20221221",
    "h5py>=3.15.1",
    "ipykernel>=7.2.0",
    "iterative-stratification>=0.1.9",
    "joblib>=1.5.3",
    "lifelines>=0.30.0",
    "lightning>=2.6.1",
    "nbformat>=5.10.4",
    "neurokit2>=0.2.12",
    "numpy>=2.4.2",
    "pandarallel>=1.6.5",
    "pandas>=3.0.1",
    "pathlib>=1.0.1",
    "plotly>=6.8.0",
    "pykeops>=2.3",
    "scikit-learn>=1.8.0",
    "setuptools>=82.0.0",
    "timm>=1.0.25",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "transformers>=5.2.0",
    "typer>=0.24.1",
    "wandb>=0.25.0",
    "wfdb>=4.3.1",
    "xlstm>=2.0.5",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["bench_xecg"]
