wandb_log: true
wandb_group: best_trans_lp

epochs: 30
lr_head: .001
lr_core: .0001
wd: 0.1
linear_probing: true
deterministic: false

batch_size: 256

data_folder_deepbeat: /scratch/datasets/DeepBeat_PPG

num_workers: 64
data_pct: 0.05

embedding_size: 768
encoder_type: transformer
checkpoint: pretrained_models/transformer.ckpt

cls_type: avg

plot_predictions: true

max_length_signal: 1000