wandb_log: true
wandb_group: best_trans_ft

epochs: 30
lr_head: .001
lr_core: .0001
wd: 0.1

linear_probing: false
deterministic: false

batch_size: 256

embedding_size: 768
encoder_type: transformer
checkpoint: pretrained_models/transformer.ckpt

data_folder_deepbeat: /scratch/datasets/DeepBeat_PPG
drop_path_prob: 0.5 # 0.75
layerwise_lr_decay: 0.75 # 0.75

num_workers: 64
data_pct: 0.05

cls_type: avg

max_length_signal: 1000

