# training hyperparameters
epochs: 100
lr: 0.001
reconstruction_lr: 0.001
wd: 0.0001
final_wd: 0.0001
dropout: 0.3
grad_clip: 0.5
precision: 16-mixed  
log_gradients: true

# optimize and scheduler
optimizer: adamw
use_scheduler: true
num_epochs_warmup: 2
num_epochs_warm_restart: 10
sched_decay_factor: 0.8
patience: 10


# dataloaders
batch_size: 192
num_workers: 32
deterministic: true

# pretrain losses params
loss_type: mse_grad_min_max
grad_loss_lambda: 1.0
min_max_loss_lambda: 1.0

# model hyperparameters
patch_size: 25
embedding_size: 128
activation_fn: gelu
xlstm_config: [ 'm', 's', 'm', 's', 'm', 's', 'm' ]
wandb_log: true
num_heads: 4
encoder_type: original
weight_tying: false
patch_embedding: linear
bidirectional: false
strategy: 'sim_dino_v2' # masked_token_prediction
mask_ratio: 0.5 # only for masked_token_prediction
monitor_metric: val_nrmse
monitor_delay_epochs: 2
use_final_layer_norm: true
cls_normalization: null
max_length_signal: 1200
proj_factor: 2
incart_win_len: 12

use_transformer: false


# jepa like args
use_teacher_student: false
ema_0: 0.996 
ema_1: 1.
start_train_head_at_epoch: 0

# data and augmentations hyperparameters
normalize: true
nk_clean: true
shift_baseline_wander_in_sample: false
shuffle_baseline_wander_in_batch: true
random_crop: 0.9
random_drop_leads: 0
keep_lead_II: true
random_surrogate_prob: 0
random_jitter_prob: 0
random_change_amplitude: 0.
pretrain_datasets: ['code', 'mimic', 'ptbxl']
masking_type: 'random' # 'random' or 'block'
leads: ['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']

# dataset folders
win_len: 1800
data_folder_code15: /media/Volume/data/CODE15/processed/
labels_file_code15: /media/Volume/data/CODE15/exams.csv
data_folder_mimic: /media/Volume/data/MIMIC_IV/

data_folder_mit: null
data_folder_ptbxl: null

data_folder_chapman: /media/Volume/data/ChapmanNingbo/1.0.0/
labels_file_chapman: /media/Volume/data/ChapmanNingbo/1.0.0/exams_filtered.csv
data_folder_incart: /media/Volume/data/incart/
data_folder_heedb: /media/Volume/data/HEEDB/

# other
debug: false

n_local_view: 0
n_global_view: 2

sampling_freq: 100
lambda_code_rate: 0.1

# mit bih 
win_len: 1800
context_len: 0
skip_majority_class_samples: false
split_val_by_patient: true