wandb_log: true
wandb_group: best_trans_lp

epochs: 20
batch_size: 64

lr_head: 0.0001
wd: 0.1

linear_probing: true
deterministic: false

embedding_size: 768
encoder_type: transformer
checkpoint: pretrained_models/transformer.ckpt
cls_type: avg

data_folder_sleep_apnea:  /home/datasets/sleep_apnea/physionet_apnea/

window_size: 10
context_size: 0