# training loop hyp
wandb_log: true
wandb_group: best_ecgcpc_ft

wd: 0.001
batch_size: 256
epochs: 30

lr_head: 0.1
lr_core: 0.1
discriminative_lr_factor: 0.1
precision: '32'
split_signal: false

linear_probing: false
deterministic: false

use_ecg_cpc: true

skip_majority_class_samples: true
use_class_weights: true
split_val_by_patient: true

win_len: 1200

data_folder_mit: /home/datasets/MIT-BIH_arrhythmia/
r_peaks_detection: true
plot_predictions: false
normalize: false