# training loop hyp
wandb_log: true
wandb_group: best_jepa_lp

lr_head: .01
epochs: 30

wd: 0.1
linear_probing: true
deterministic: false
batch_size: 96
num_workers: 64

use_ecg_jepa: true

skip_majority_class_samples: true
use_class_weights: true
split_val_by_patient: true

data_folder_mit: /home/datasets/MIT-BIH_arrhythmia/

r_peaks_detection: true
original_freq: 360
plot_predictions: false