# training loop hyp
wandb_log: true
wandb_group: best_stmem_ft

lr_head: .01
lr_core: .01
epochs: 30

wd: 0.1
dropout: 0.
linear_probing: false
deterministic: false
batch_size: 96
num_workers: 64

use_st_mem: true

drop_path_prob: 0.5
layerwise_lr_decay: 0.75

skip_majority_class_samples: true
use_class_weights: true
split_val_by_patient: true

data_folder_mit: /home/datasets/MIT-BIH_arrhythmia/

r_peaks_detection: true
original_freq: 360
plot_predictions: false
win_len: 1125