# training loop hyp
wandb_log: true
wandb_group: best_trans_lp
epochs: 20
wd: 0.1
batch_size: 512

lr_head: 0.001

linear_probing: true
deterministic: false

embedding_size: 768
encoder_type: transformer
checkpoint: pretrained_models/transformer.ckpt

use_final_layer_norm: false
cls_normalization: batch  # 'batch', 'layer', 'instance'

data_folder_mimic: /scratch/datasets/mimic-iv-ecg/raw/


training_pct: 1.
