# training loop hyp
wandb_log: true
wandb_group: best_ecgcpc_ft
wd: 0.001

lr_head: 0.03
lr_core: 0.03
discriminative_lr_factor: 0.1
precision: '32'
split_signal: false

linear_probing: false
deterministic: false
cls_normalization: null

use_ecg_cpc: true

data_folder_mimic: /groups/dlaskalab/mimic-iv-ecg/raw/
data_folder_code15: /groups/dlaskalab/CODE15/processed/
labels_file_code15: /groups/dlaskalab/CODE15/processed/exams_filtered.csv
data_folder_ptbxl: /groups/dlaskalab/ptb-xl/raw/1.0.3/records500/
data_folder_cpsc2018: /groups/dlaskalab/CPSC2018/
