# training loop hyp
wandb_log: true
wandb_group: best_ecgfm_ft

lr_head: .1
lr_core: .001
wd: 0.01

dropout: 0.
linear_probing: false
deterministic: false

use_ecg_founder: true

drop_path_prob: 0.
layerwise_lr_decay: 0.

data_folder_mimic: /groups/dlaskalab/mimic-iv-ecg/raw/
data_folder_code15: /groups/dlaskalab/CODE15/processed/
labels_file_code15: /groups/dlaskalab/CODE15/processed/exams_filtered.csv
data_folder_ptbxl: /groups/dlaskalab/ptb-xl/raw/1.0.3/records500/
data_folder_cpsc2018: /groups/dlaskalab/CPSC2018/

max_length_signal: 5000
normalize: false
