# training loop hyp
wandb_log: true
wandb_group: best_stmem_lp

lr_head: .01
wd: 0.01

linear_probing: true
deterministic: false

use_st_mem: true

data_folder_mimic: /scratch/datasets/mimic-iv-ecg/raw/


data_folder_code15: /scratch/datasets/CODE15/processed/
labels_file_code15: /scratch/datasets/CODE15/processed/exams_filtered.csv

data_folder_ptbxl: /scratch/datasets/ptb-xl/raw/1.0.3/records500/


data_folder_cpsc2018: /home/datasets/CPSC2018/
max_length_signal: 2325