# training loop hyp
wandb_log: true
wandb_group: best_trans_ft

wd: 0.01

lr_head: 0.01
lr_core: 0.0001
drop_path_prob: 0.
layerwise_lr_decay: 0.75 

linear_probing: false
deterministic: false

embedding_size: 768
encoder_type: transformer
# checkpoint: pretrain-xLSTM/iw88p22s/checkpoints/epoch=49-step=504700.ckpt

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'

data_folder_mimic: /scratch/datasets/mimic-iv-ecg/raw/


data_folder_code15: /scratch/datasets/CODE15/processed/
labels_file_code15: /scratch/datasets/CODE15/processed/exams_filtered.csv

data_folder_ptbxl: /scratch/datasets/ptb-xl/raw/1.0.3/records500/

data_folder_cpsc2018: /home/datasets/CPSC2018/


max_length_signal: 1000