# training loop hyp
wandb_log: true
wandb_group: best_trans_lp

wd: 0.01
lr_head: 0.01

linear_probing: false
deterministic: false

embedding_size: 768
encoder_type: transformer
checkpoint: /home/hpcusers/q036rl/MIT-BIH_ecg_arrhytmia/pretrained_models/transformer.ckpt

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'

data_folder_mimic: /groups/dlaskalab/mimic-iv-ecg/raw/
data_folder_code15: /groups/dlaskalab/CODE15/processed/
labels_file_code15: /groups/dlaskalab/CODE15/processed/exams_filtered.csv
data_folder_ptbxl: /groups/dlaskalab/ptb-xl/raw/1.0.3/records500/
data_folder_cpsc2018: /groups/dlaskalab/CPSC2018/

max_length_signal: 1000