# training loop hyp
wandb_log: true
wandb_group: best_ecgcpc_ft

wd: 0.001
batch_size: 8

lr_head: 1.
lr_core: 1.
discriminative_lr_factor: 0.1
precision: '32'
split_signal: false

linear_probing: false
deterministic: false

use_ecg_cpc: true
use_class_weights: true

max_length_signal: 2400

data_folder_high_intensity: /home/datasets/ECG_high_intensity_exercise
r_peaks_detection: true
plot_predictions: false
normalize: false