wandb_log: true
wandb_group: best_xlstm_sup

batch_size: 8

epochs: 30

lr_head: 0.001
lr_core: 0.001

layerwise_lr_decay: 0.
drop_path_prob: 0.
wd: 0.

linear_probing: false
deterministic: false

embedding_size: 1024
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
# checkpoint: pretrain-xLSTM/0rgc8fun/checkpoints/epoch=49-step=504700.ckpt

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'
patch_embedding: linear


data_folder_high_intensity: /home/datasets/ECG_high_intensity_exercise

r_peaks_detection: true
plot_predictions: false

max_length_signal: 2000