# training loop hyp
wandb_log: true
wandb_group: best_xlstm_lp
epochs: 30
wd: 0.1
batch_size: 256

lr_head: 0.001

linear_probing: true
deterministic: false

embedding_size: 1024
encoder_type: vanilla
xlstm_config: ["s","s","m","m","s","s","m","m","s"]
checkpoint: pretrain-xLSTM/0rgc8fun/checkpoints/epoch=49-step=504700.ckpt

use_final_layer_norm: false
cls_normalization: null  # 'batch', 'layer', 'instance'
cls_type: max

data_folder_cpsc2018: /data/groups/dlaskalab/CPSC2018/


max_length_signal: 5000

training_pct: 1.